### ISSUE TITLE
Exception when using *.xmltv.properties named file

### ISSUE THREAD

**Issue by jwittkoski** [jzhvymetal/SageTv_XMLTVImportPlugin#1]
Using the latest v3.1 on Ubuntu.

Initially I had my config file named `xmltv_Pluto.xmltv.properties`. I did not create an `xmltv.properties` file.

But when trying to add a new source an exception is thrown and no config file is loaded:

```
16-12-2023 00:53:27,865 java.lang.NullPointerException
	at xmltv.XMLTVImportPlugin.logger(XMLTVImportPlugin.java:882)
	at xmltv.XMLTVImportPlugin.log(XMLTVImportPlugin.java:869)
	at xmltv.XMLTVImportPlugin.readConfigurations(XMLTVImportPlugin.java:680)
	at xmltv.XMLTVImportPlugin.getProviders(XMLTVImportPlugin.java:648)
	at xmltv.XMLTVImportPlugin.getProviderArray(XMLTVImportPlugin.java:985)
	at xmltv.XMLTVImportPlugin.getProviders(XMLTVImportPlugin.java:1037)
	at sage.EPG.getProviders(EPG.java:1565)
	at sage.EPG.getProvidersAndCacheNames(EPG.java:1576)
	at sage.api.Global$24.runSafely(Global.java:419)
	at sage.PredefinedJEPFunction.run(PredefinedJEPFunction.java:110)
	at sage.jep.JEP$CommandEvaluator.evaluate(JEP.java:586)
	at sage.jep.JEP.getValueAsObject(JEP.java:428)
	at sage.Catbert.evaluateExpression(Catbert.java:641)
	at sage.ZPseudoComp.processChain(ZPseudoComp.java:4641)
	at sage.ZPseudoComp.processChain(ZPseudoComp.java:4579)
	at sage.ZPseudoComp.actionPerformed(ZPseudoComp.java:4562)
	at sage.ZPseudoComp.action(ZPseudoComp.java:3800)
	at sage.PseudoMenu.action(PseudoMenu.java:220)
	at sage.EventRouter.processUserEvent(EventRouter.java:876)
	at sage.EventRouter.run(EventRouter.java:936)
	at java.lang.Thread.run(Thread.java:748)
```

It appears that when first checking for the `xmltv.properties` file, if it doesn't exist, the log call in the catch (line 680) is throwing another exception.

If I rename my file to `xmltv.properties` it does not throw an exception and I am able to use the plugin.

**Comment by Retired-it** [comment]
For sagetv 9 running in windows 11, 
I found that if you have an empty xmltv.properties  I.E Nothing in it!
then the actual file (for my example: xmltv_gracenote.xmltv.properties) will be loaded, and thus you can have multiple different provider names, i.e.  provider.name=gracenote.com  in the various different properties files.

Thanks to @jzhvymetal  For providing his xmltv_gracenote.xmltv.properties, which I modified to have comments, and have 'Run.before' etc working correctly.
